/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package treinamento;

import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Marcelino
 */
public class formJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public formJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        Configurações = new javax.swing.JMenuItem();
        Posição = new javax.swing.JMenuItem();
        pnlDadosPessoais = new javax.swing.JPanel();
        lblDadosPessoais = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edtCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        edtNumero = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        edtBairro = new javax.swing.JTextField();
        edtCidade = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        edtCep = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        edtTelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        edtRG = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        edtEMail1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edtDataCadastro = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edtDataNascimento = new javax.swing.JTextField();
        pnlDadosComplementares = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        edtEmail2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        edtLocalTrabalho = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        edtFone2 = new javax.swing.JTextField();
        lblEstadoCivil = new javax.swing.JLabel();
        edtEstadoCivil = new javax.swing.JTextField();
        edtEscolaridade = new javax.swing.JTextField();
        lblEscolaridade = new javax.swing.JLabel();
        lblObs = new javax.swing.JLabel();
        edtObs = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnLimparCampos = new javax.swing.JButton();
        btnPreencherCampos = new javax.swing.JButton();
        btnDesabilitarCampos = new javax.swing.JButton();
        btnHabilitarCampos = new javax.swing.JButton();
        btnClearFields = new javax.swing.JButton();
        btnDisableFields = new javax.swing.JButton();
        btnEnableFields = new javax.swing.JButton();
        btnFillInFields = new javax.swing.JButton();
        btnContaComponentes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnClearInstanceOf = new javax.swing.JButton();
        btnClearFieldsInstanceOfMethod = new javax.swing.JButton();

        Configurações.setText("Configurações");
        Configurações.setActionCommand("Configuracoes");
        popupMenu.add(Configurações);

        Posição.setText("Posicao");
        Posição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosiçãoActionPerformed(evt);
            }
        });
        popupMenu.add(Posição);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        pnlDadosPessoais.setBackground(new java.awt.Color(204, 255, 204));

        lblDadosPessoais.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDadosPessoais.setForeground(new java.awt.Color(51, 51, 255));
        lblDadosPessoais.setText("Dados Pessoais");

        lblCodigo.setText("Código:");

        edtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCodigoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        edtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEnderecoActionPerformed(evt);
            }
        });

        lblNumero.setText("Número:");

        edtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNumeroActionPerformed(evt);
            }
        });

        lblBairro.setText("Bairro:");

        lblCidade.setText("Cidade:");

        lblCep.setText("Cep:");

        lblTelefone.setText("Telefone");

        edtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTelefoneActionPerformed(evt);
            }
        });

        jLabel8.setText("RG:");

        lblEmail1.setText("Email:");

        edtEMail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEMail1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Data de Cadastro:");

        lblCPF.setText("CPF:");

        jLabel3.setText("Data Nascimento:");

        edtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDataNascimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosPessoaisLayout = new javax.swing.GroupLayout(pnlDadosPessoais);
        pnlDadosPessoais.setLayout(pnlDadosPessoaisLayout);
        pnlDadosPessoaisLayout.setHorizontalGroup(
            pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosPessoaisLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edtEMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(lblCep, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(edtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(edtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosPessoaisLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(lblBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(edtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDadosPessoaisLayout.setVerticalGroup(
            pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDadosPessoais)
                .addGap(7, 7, 7)
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero)
                    .addComponent(edtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCep)
                    .addComponent(edtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidade)
                    .addComponent(edtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBairro)
                    .addComponent(edtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone)
                    .addComponent(jLabel8)
                    .addComponent(edtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPF)
                    .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail1)
                    .addComponent(edtEMail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(edtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(edtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE))
        );

        pnlDadosComplementares.setBackground(new java.awt.Color(255, 204, 204));
        pnlDadosComplementares.setMinimumSize(new java.awt.Dimension(100, 80));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("Dados Complementares:");

        jLabel12.setText("Email:");

        jLabel13.setText("Local de Trabalho:");

        edtLocalTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtLocalTrabalhoActionPerformed(evt);
            }
        });

        jLabel14.setText("Fone2:");

        lblEstadoCivil.setText("Estado Cívil:");

        lblEscolaridade.setText("Escolaridade:");

        lblObs.setText("Observação:");

        javax.swing.GroupLayout pnlDadosComplementaresLayout = new javax.swing.GroupLayout(pnlDadosComplementares);
        pnlDadosComplementares.setLayout(pnlDadosComplementaresLayout);
        pnlDadosComplementaresLayout.setHorizontalGroup(
            pnlDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosComplementaresLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDadosComplementaresLayout.createSequentialGroup()
                        .addComponent(lblObs, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtObs))
                    .addGroup(pnlDadosComplementaresLayout.createSequentialGroup()
                        .addGroup(pnlDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosComplementaresLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtFone2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(lblEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDadosComplementaresLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtEstadoCivil)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addGroup(pnlDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosComplementaresLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtLocalTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosComplementaresLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlDadosComplementaresLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlDadosComplementaresLayout.setVerticalGroup(
            pnlDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosComplementaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(pnlDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(edtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(edtLocalTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(edtFone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoCivil)
                    .addComponent(edtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEscolaridade))
                .addGap(18, 18, 18)
                .addGroup(pnlDadosComplementaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObs)
                    .addComponent(edtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        btnPreencherCampos.setText("Preencher Campos");
        btnPreencherCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreencherCamposActionPerformed(evt);
            }
        });

        btnDesabilitarCampos.setText("Desabilitar Campos");
        btnDesabilitarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesabilitarCamposActionPerformed(evt);
            }
        });

        btnHabilitarCampos.setText("Habilitar Campos");
        btnHabilitarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarCamposActionPerformed(evt);
            }
        });

        btnClearFields.setText("Clear Fields");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });

        btnDisableFields.setText("Desabilitar Campos");
        btnDisableFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisableFieldsActionPerformed(evt);
            }
        });

        btnEnableFields.setText("Habilitar Campos");
        btnEnableFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableFieldsActionPerformed(evt);
            }
        });

        btnFillInFields.setText("Preencher Campos");
        btnFillInFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFillInFieldsActionPerformed(evt);
            }
        });

        btnContaComponentes.setText("ContaComponentes PnDadosPessoais");
        btnContaComponentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContaComponentesActionPerformed(evt);
            }
        });

        jButton1.setText("Conta Componentes com InstanceOf");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnClearInstanceOf.setText("Limpar Campos com Instance Of");
        btnClearInstanceOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearInstanceOfActionPerformed(evt);
            }
        });

        btnClearFieldsInstanceOfMethod.setText("Limpar Campos com InstanceOf Metodos");
        btnClearFieldsInstanceOfMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsInstanceOfMethodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLimparCampos)
                        .addGap(18, 18, 18)
                        .addComponent(btnPreencherCampos)
                        .addGap(18, 18, 18)
                        .addComponent(btnDesabilitarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(btnHabilitarCampos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnClearFields)
                        .addGap(18, 18, 18)
                        .addComponent(btnFillInFields)
                        .addGap(18, 18, 18)
                        .addComponent(btnDisableFields)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClearFieldsInstanceOfMethod)
                            .addComponent(btnEnableFields, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContaComponentes)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnClearInstanceOf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparCampos)
                    .addComponent(btnPreencherCampos)
                    .addComponent(btnDesabilitarCampos)
                    .addComponent(btnHabilitarCampos)
                    .addComponent(btnContaComponentes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearFields)
                    .addComponent(btnDisableFields)
                    .addComponent(btnEnableFields)
                    .addComponent(btnFillInFields)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearFieldsInstanceOfMethod)
                    .addComponent(btnClearInstanceOf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDadosComplementares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDadosPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDadosComplementares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        if (evt.isPopupTrigger()){
            // Mostra o popup na posição do mouse
            popupMenu.show(evt.getComponent(),evt.getX(),evt.getY());
            // Mostra o popop em uma posição fixa;
           // popupMenu.show(this, 100,00);
            // Só mostra o popup
           // popupMenu.setVisible(true);
        }
    }//GEN-LAST:event_formMouseReleased

    
    private void PosiçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosiçãoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Teste Event");
    }//GEN-LAST:event_PosiçãoActionPerformed

    private void edtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCodigoActionPerformed

    private void edtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEnderecoActionPerformed

    private void edtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNumeroActionPerformed

    private void edtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTelefoneActionPerformed

    private void edtEMail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEMail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEMail1ActionPerformed

    private void edtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDataNascimentoActionPerformed

    private void edtLocalTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtLocalTrabalhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtLocalTrabalhoActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        edtCodigo.setText("");
        edtBairro.setText("");
        edtCPF.setText("");
        edtCep.setText("");
        edtCidade.setText("");
        edtCodigo.setText("");
        edtDataCadastro.setText("");
        edtDataNascimento.setText("");
        edtEMail1.setText("");
        edtEmail2.setText("");
        edtEndereco.setText("");
        edtEscolaridade.setText("");
        edtEstadoCivil.setText("");
        edtFone2.setText("");
        edtLocalTrabalho.setText("");
        edtNome.setText("");
        edtNumero.setText("");
        edtObs.setText("");
        edtRG.setText("");
        edtTelefone.setText("");
        
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnPreencherCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreencherCamposActionPerformed
        edtCodigo.setText("123456");
        edtBairro.setText("Tijucal");
        edtCPF.setText("07756074874");
        edtCep.setText("78088120");
        edtCidade.setText("Cuiabá");
        edtDataCadastro.setText("05/05/2024");
        edtDataNascimento.setText("30/10/1967");
        edtEMail1.setText("marcelino.feliciano@hotmail.com");
        edtEmail2.setText("marcelino.feliciano@outlook.com");
        edtEndereco.setText("Rua duzentos e hum, 6");
        edtEscolaridade.setText("Superior Completo");
        edtEstadoCivil.setText("Casado");
        edtFone2.setText("(65) 98141-3390");
        edtLocalTrabalho.setText("Home Office");
        edtNome.setText("Marcelino");
        edtNumero.setText("6");
        edtObs.setText("Preenchimento Automático");
        edtRG.setText("185006139");
        edtTelefone.setText("(65) 98141-3390");
    }//GEN-LAST:event_btnPreencherCamposActionPerformed

    private void btnDesabilitarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesabilitarCamposActionPerformed
        edtCodigo.setEnabled(false);
        edtBairro.setEnabled(false);
        edtCPF.setEnabled(false);
        edtCep.setEnabled(false);
        edtCidade.setEnabled(false);
        edtCodigo.setEnabled(false);
        edtDataCadastro.setEnabled(false);
        edtDataNascimento.setEnabled(false);
        edtEMail1.setEnabled(false);
        edtEmail2.setEnabled(false);
        edtEndereco.setEnabled(false);
        edtEscolaridade.setEnabled(false);
        edtEstadoCivil.setEnabled(false);
        edtFone2.setEnabled(false);
        edtLocalTrabalho.setEnabled(false);
        edtNome.setEnabled(false);
        edtNumero.setEnabled(false);
        edtObs.setEnabled(false);
        edtRG.setEnabled(false);
        edtTelefone.setEnabled(false);
        
    }//GEN-LAST:event_btnDesabilitarCamposActionPerformed

    private void btnHabilitarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarCamposActionPerformed
        edtCodigo.setEnabled(true);
        edtBairro.setEnabled(true);
        edtCPF.setEnabled(true);
        edtCep.setEnabled(true);
        edtCidade.setEnabled(true);
        edtCodigo.setEnabled(true);
        edtDataCadastro.setEnabled(true);
        edtDataNascimento.setEnabled(true);
        edtEMail1.setEnabled(true);
        edtEmail2.setEnabled(true);
        edtEndereco.setEnabled(true);
        edtEscolaridade.setEnabled(true);
        edtEstadoCivil.setEnabled(true);
        edtFone2.setEnabled(true);
        edtLocalTrabalho.setEnabled(true);
        edtNome.setEnabled(true);
        edtNumero.setEnabled(true);
        edtObs.setEnabled(true);
        edtRG.setEnabled(true);
        edtTelefone.setEnabled(true);
    }//GEN-LAST:event_btnHabilitarCamposActionPerformed

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        //JTextField campoCodigo = edtCodigo;
        //campoCodigo.setText("");
        JTextField[] fields = fieldsClient();
        for(int i=0; i < fields.length; i++){
            fields[i].setText("");
        }
    }//GEN-LAST:event_btnClearFieldsActionPerformed

    
    private void btnFillInFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFillInFieldsActionPerformed
         JTextField[] fields = fieldsClient();
        for(int i=0; i < fields.length; i++){
            fields[i].setText("marcelino");
        }
    }//GEN-LAST:event_btnFillInFieldsActionPerformed

    private void btnDisableFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisableFieldsActionPerformed
        JTextField[] fields = fieldsClient();
        for(int i=0; i < fields.length; i++){
            fields[i].setEnabled(false);
        }
    }//GEN-LAST:event_btnDisableFieldsActionPerformed

    private void btnEnableFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableFieldsActionPerformed
         JTextField[] fields = fieldsClient();
        for(int i=0; i < fields.length; i++){
            fields[i].setEnabled(true);
        }
    }//GEN-LAST:event_btnEnableFieldsActionPerformed

    private void btnContaComponentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContaComponentesActionPerformed
       Component[] componentes = pnlDadosPessoais.getComponents();
       // Conta componentes forma 1
       /*
       int conta=0;
       for (int i=0; i <componentes.length; i++){
           conta++;
       }
       JOptionPane.showMessageDialog(null, conta);
       */
       // conta componentents forma 2
       //int conta = componentes.length;
       //
       // JOptionPane.showMessageDialog(null, conta);
       // conta componentents forma 3
       //
       JOptionPane.showMessageDialog(null, componentes.length);
     
       
       
    }//GEN-LAST:event_btnContaComponentesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Component[] components = pnlDadosPessoais.getComponents();
    
       int contaJTextField = 0, contaJLabel = 0;
       
       for (int i=0; i <components.length; i++){
           if (components[i] instanceof JTextField){
               contaJTextField++;
           } else if (components[i] instanceof JLabel){
              contaJLabel++;
           }
       }
       
       JOptionPane.showMessageDialog(null,"JTextField: "+contaJTextField + "\nJLabel: "+contaJLabel);       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnClearInstanceOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearInstanceOfActionPerformed
       Component[] components = pnlDadosPessoais.getComponents();
       
       for (int i=0; i <components.length; i++){
           if (components[i] instanceof JTextField){
               JTextField fields = (JTextField) components[i];
               fields.setText("");
           }
       }
       components = pnlDadosComplementares.getComponents();
       
       for (int i=0; i <components.length; i++){
           if (components[i] instanceof JTextField){
               JTextField fields = (JTextField) components[i];
               fields.setText("");
           }
       }
     
      
    }//GEN-LAST:event_btnClearInstanceOfActionPerformed

    private void btnClearFieldsInstanceOfMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsInstanceOfMethodActionPerformed
       clearsFields( pnlDadosPessoais);
       clearsFields( pnlDadosComplementares );
    }//GEN-LAST:event_btnClearFieldsInstanceOfMethodActionPerformed
    
    private void clearsFields( JPanel panel){
        
        Component[] components = panel.getComponents();
        for (int i=0; i < components.length; i++){
           if (components[i] instanceof JTextField){
               JTextField fields = (JTextField) components[i];
               fields.setText("");
           }
       } 
    }
    private JTextField[] fieldsClient(){
        JTextField[] fields ={ edtCodigo,
        edtNome, edtLocalTrabalho,edtDataNascimento,edtRG, edtCPF, edtEMail1,edtEmail2, edtEscolaridade, edtEstadoCivil,
        edtFone2,edtCep, edtEndereco, edtNumero,edtBairro, edtCidade,edtTelefone,edtDataCadastro,edtObs };
        
        return fields;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Configurações;
    private javax.swing.JMenuItem Posição;
    private javax.swing.JButton btnClearFields;
    private javax.swing.JButton btnClearFieldsInstanceOfMethod;
    private javax.swing.JButton btnClearInstanceOf;
    private javax.swing.JButton btnContaComponentes;
    private javax.swing.JButton btnDesabilitarCampos;
    private javax.swing.JButton btnDisableFields;
    private javax.swing.JButton btnEnableFields;
    private javax.swing.JButton btnFillInFields;
    private javax.swing.JButton btnHabilitarCampos;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnPreencherCampos;
    private javax.swing.JTextField edtBairro;
    private javax.swing.JTextField edtCPF;
    private javax.swing.JTextField edtCep;
    private javax.swing.JTextField edtCidade;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtDataCadastro;
    private javax.swing.JTextField edtDataNascimento;
    private javax.swing.JTextField edtEMail1;
    private javax.swing.JTextField edtEmail2;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtEscolaridade;
    private javax.swing.JTextField edtEstadoCivil;
    private javax.swing.JTextField edtFone2;
    private javax.swing.JTextField edtLocalTrabalho;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtNumero;
    private javax.swing.JTextField edtObs;
    private javax.swing.JTextField edtRG;
    private javax.swing.JTextField edtTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDadosPessoais;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEscolaridade;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnlDadosComplementares;
    private javax.swing.JPanel pnlDadosPessoais;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
}
